/**
 * FILE: js/services/api.js
 * CHỨC NĂNG: Cung cấp dữ liệu bản đồ (Đã bỏ Time và Weight)
 */

async function fetchMapData() {
    // Giả lập độ trễ mạng
    await new Promise(r => setTimeout(r, 50));
    const rawData = {
        nodes: [
            { Id: '1.1', Name: 'Cổng ngoài', X: 39.0, Y: 96.6, Type: 'Red' },
            { Id: '1.2', Name: 'Cổng ngoài', X: 64.0, Y: 96.4, Type: 'Red' },
            { Id: '2', Name: 'Tòa B1', X: 30.0, Y: 69.1, Type: 'Red' },
            { Id: '3', Name: 'Cổng trong', X: 51.4, Y: 60.0, Type: 'Red' },
            { Id: '4', Name: 'Tòa A1', X: 51.4, Y: 53.3, Type: 'Red' },
            { Id: '5', Name: 'Tòa A2', X: 41.0, Y: 48.6, Type: 'Red' },
            { Id: '6', Name: 'Tòa B2', X: 16.0, Y: 51.8, Type: 'Red' },
            { Id: '7', Name: 'Thư viện', X: 7.2, Y: 48.6, Type: 'Red' },
            { Id: '8.1', Name: 'Kí túc xá C3', X: 19.0, Y: 39.6, Type: 'Red' },
            { Id: '8.2', Name: 'Kí túc xá C3', X: 27.0, Y: 39.6, Type: 'Red' },
            { Id: '9', Name: 'Kí túc xá C4', X: 8.6, Y: 39.6, Type: 'Red' },
            { Id: '10', Name: 'Trạm gửi xe 1', X: 19.0, Y: 33.0, Type: 'Red' },
            { Id: '11', Name: 'Tòa D2', X: 19.0, Y: 26.0, Type: 'Red' },
            { Id: '12.2', Name: 'Hội trường D1', X: 42.5, Y: 26.0, Type: 'Red' },
            { Id: '12.1', Name: 'Hội trường D1', X: 57.0, Y: 26.0, Type: 'Red' },
            { Id: '13', Name: 'Trạm gửi xe 2', X: 69.2, Y: 22.5, Type: 'Red' },
            { Id: '14.1', Name: 'Kí túc xá C2', X: 80.5, Y: 37.5, Type: 'Red' },
            { Id: '14.2', Name: 'Kí túc xá C2', X: 76.5, Y: 37.5, Type: 'Red' },
            { Id: '15', Name: 'Cổng sau', X: 96.5, Y: 33.0, Type: 'Red' },
            { Id: '16', Name: 'Kí túc xá C1', X: 94.5, Y: 37.5, Type: 'Red' },
            { Id: '17', Name: 'Văn phòng đoàn', X: 76.5, Y: 56.5, Type: 'Red' },
            { Id: '18', Name: 'Sân thể dục', X: 72.5, Y: 26.0, Type: 'Red' },
            { Id: '19', Name: 'Tòa D3', X: 90.5, Y: 26.0, Type: 'Red' },
            { Id: '20', Name: 'Sân pickeball', X: 76.5, Y: 13.8, Type: 'Red' },
            { Id: '21', Name: 'Sân bóng', X: 87.5, Y: 11.5, Type: 'Red' },
            { Id: '22', Name: 'Tòa D5', X: 62.5, Y: 14.2, Type: 'Red' },
            { Id: '23', Name: 'Tòa D4', X: 37.0, Y: 14.0, Type: 'Red' },
            { Id: '24', Name: 'Tòa D6', X: 41.0, Y: 5.5, Type: 'Red' },
            { Id: '25', Name: 'Nhà sách', X: 30.0, Y: 5.5, Type: 'Red' },
            { Id: '26', Name: 'Căng tin', X: 12.2, Y: 5.5, Type: 'Red' },
            { Id: '27', Name: 'Nhà thể chất', X: 12.2, Y: 14.0, Type: 'Red' },
            { Id: '28', Name: 'Trạm gửi xe 3', X: 19.0, Y: 19.2, Type: 'Red' },
            { Id: '29', Name: 'Phòng bảo vệ', X: 30.0, Y: 60.7, Type: 'Red' },
            { Id: 'F4', Name: 'F4', X: 39.0, Y: 69.1 },
            { Id: 'F5', Name: 'F5', X: 39.0, Y: 62.1 },
            { Id: 'F6', Name: 'F6', X: 51.4, Y: 62.1 },
            { Id: 'F7', Name: 'F7', X: 64.0, Y: 62.1 },
            { Id: 'F8', Name: 'F8', X: 51.4, Y: 56.5 },
            { Id: 'F9', Name: 'F9', X: 30.0, Y: 56.5 },
            { Id: 'F10', Name: 'F10', X: 30.0, Y: 48.6 },
            { Id: 'F11', Name: 'F11', X: 16.0, Y: 48.6 },
            { Id: 'F12', Name: 'F12', X: 30.0, Y: 39.6 },
            { Id: 'F13', Name: 'F13', X: 13.5, Y: 39.6 },
            { Id: 'F14', Name: 'F14', X: 30.0, Y: 33.0 },
            { Id: 'F15', Name: 'F15', X: 13.5, Y: 33.0 },
            { Id: 'F19', Name: 'F19', X: 87.5, Y: 37.5 },
            { Id: 'F20', Name: 'F20', X: 69.2, Y: 37.5 },
            { Id: 'F21', Name: 'F21', X: 87.5, Y: 33.0 },
            { Id: 'F23', Name: 'F23', X: 69.2, Y: 33.0 },
            { Id: 'F26', Name: 'F26', X: 69.2, Y: 26.0 },
            { Id: 'F27', Name: 'F27', X: 30.0, Y: 26.0 },
            { Id: 'F28', Name: 'F28', X: 30.0, Y: 19.2 },
            { Id: 'F29', Name: 'F29', X: 41.0, Y: 19.2 },
            { Id: 'F30', Name: 'F30', X: 58.5, Y: 19.2 },
            { Id: 'F31', Name: 'F31', X: 69.2, Y: 19.2 },
            { Id: 'F32', Name: 'F32', X: 76.5, Y: 19.2 },
            { Id: 'F33', Name: 'F33', X: 87.5, Y: 19.2 },
            { Id: 'F36', Name: 'F36', X: 58.5, Y: 14.2 },
            { Id: 'F37', Name: 'F37', X: 58.5, Y: 7.5 },
            { Id: 'F38', Name: 'F38', X: 41.0, Y: 7.5 },
            { Id: 'F39', Name: 'F39', X: 41.0, Y: 14.0 },
            { Id: 'F40', Name: 'F40', X: 30.0, Y: 14.0 },
            { Id: 'F41', Name: 'F41', X: 30.0, Y: 7.5 },
            { Id: 'F42', Name: 'F42', X: 12.2, Y: 7.5 },
            { Id: 'F47', Name: 'F47', X: 12.2, Y: 19.2 }

        ],
        zones: [
            { name: "Cổng ngoài", x: 240, y: 1720, width: 360, height: 80 },
            { name: "Trạm gửi xe 1", x: 40, y: 600, width: 40, height: 40 },
            { name: "Tòa D2", x: -80, y: 400, width: 160, height: 120 },
            { name: "Hội trường D1", x: 200, y: 400, width: 400, height: 200 },
            { name: "Trạm gửi xe 2", x: 600, y: 420, width: 40, height: 40 },
            { name: "Kí túc xá C2", x: 680, y: 640, width: 80, height: 160 },
            { name: "Cổng sau", x: 900, y: 600, width: 60, height: 40 },
            { name: "Kí túc xá C1", x: 880, y: 640, width: 80, height: 160 },
            { name: "Văn phòng đoàn", x: 680, y: 860, width: 80, height: 220 },
            { name: "Sân thể dục", x: 640, y: 400, width: 170, height: 160 },
            { name: "Tòa D3", x: 810, y: 400, width: 150, height: 160 },
            { name: "Tòa B1", x: 80, y: 1120, width: 160, height: 280 },
            { name: "Sân pickeball", x: 640, y: 40, width: 160, height: 260 },
            { name: "Sân bóng", x: 800, y: 40, width: 160, height: 220 },
            { name: "Tòa D5", x: 520, y: 200, width: 80, height: 160 },
            { name: "Tòa D4", x: 200, y: 200, width: 80, height: 160 },
            { name: "Tòa D6", x: 200, y: 40, width: 400, height: 120 },
            { name: "Nhà sách", x: 120, y: 40, width: 80, height: 120 },
            { name: "Căng tin", x: -160, y: 80, width: 240, height: 80 },
            { name: "Nhà thể chất", x: -160, y: 200, width: 160, height: 160 },
            { name: "Trạm gửi xe 3", x: 40, y: 360, width: 40, height: 40 },
            { name: "Phòng bảo vệ", x: 80, y: 1080, width: 160, height: 40 },
            { name: "Cổng trong", x: 240, y: 1080, width: 360, height: 40 },
            { name: "Tòa A1", x: 200, y: 920, width: 480, height: 80 },
            { name: "Tòa A2", x: 280, y: 800, width: 360, height: 120 },
            { name: "Tòa B2", x: -160, y: 920, width: 320, height: 80 },
            { name: "Thư viện", x: -160, y: 840, width: 100, height: 80 },
            { name: "Kí túc xá C3", x: 40, y: 640, width: 120, height: 200 },
            { name: "Kí túc xá C4", x: -160, y: 640, width: 140, height: 200 }
        ],
        edges: [
            // --- CÁC ĐƯỜNG NỐI ---
            { FromNodeId: 'F4', ToNodeId: 'F5' },
            { FromNodeId: 'F5', ToNodeId: 'F6' },
            { FromNodeId: 'F6', ToNodeId: 'F7' },
            { FromNodeId: 'F8', ToNodeId: 'F9' },
            { FromNodeId: 'F9', ToNodeId: 'F10' },
            { FromNodeId: 'F10', ToNodeId: 'F11' },
            { FromNodeId: 'F10', ToNodeId: 'F12' },
            { FromNodeId: 'F12', ToNodeId: 'F14' },
            { FromNodeId: 'F13', ToNodeId: 'F15' },
            { FromNodeId: 'F14', ToNodeId: 'F27' },
            { FromNodeId: 'F14', ToNodeId: 'F23' },
            { FromNodeId: 'F19', ToNodeId: 'F21' },
            { FromNodeId: 'F20', ToNodeId: 'F23' },
            { FromNodeId: 'F21', ToNodeId: 'F23' },
            { FromNodeId: 'F27', ToNodeId: 'F28' },
            { FromNodeId: 'F28', ToNodeId: 'F29' },
            { FromNodeId: 'F28', ToNodeId: 'F40' },
            { FromNodeId: 'F29', ToNodeId: 'F30' },
            { FromNodeId: 'F29', ToNodeId: 'F39' },
            { FromNodeId: 'F30', ToNodeId: 'F31' },
            { FromNodeId: 'F30', ToNodeId: 'F36' },
            { FromNodeId: 'F31', ToNodeId: 'F33' },
            { FromNodeId: 'F36', ToNodeId: 'F37' },
            { FromNodeId: 'F37', ToNodeId: 'F38' },
            { FromNodeId: 'F38', ToNodeId: 'F39' },
            { FromNodeId: 'F38', ToNodeId: 'F41' },
            { FromNodeId: 'F40', ToNodeId: 'F41' },
            { FromNodeId: 'F41', ToNodeId: 'F42' },
            { FromNodeId: '1.1', ToNodeId: 'F4' },
            { FromNodeId: '1.2', ToNodeId: 'F7' },
            { FromNodeId: '2', ToNodeId: 'F4' },
            { FromNodeId: '3', ToNodeId: 'F6' },
            { FromNodeId: '3', ToNodeId: 'F8' },
            { FromNodeId: '4', ToNodeId: 'F8' },
            { FromNodeId: '5', ToNodeId: 'F10' },
            { FromNodeId: '6', ToNodeId: 'F11' },
            { FromNodeId: '7', ToNodeId: 'F11' },
            { FromNodeId: '8.2', ToNodeId: 'F12' },
            { FromNodeId: '8.1', ToNodeId: 'F13' },
            { FromNodeId: '9', ToNodeId: 'F13' },
            { FromNodeId: '10', ToNodeId: 'F14' },
            { FromNodeId: '10', ToNodeId: 'F15' },
            { FromNodeId: '11', ToNodeId: 'F27' },
            { FromNodeId: '12.2', ToNodeId: 'F27' },
            { FromNodeId: '12.1', ToNodeId: 'F26' },
            { FromNodeId: '13', ToNodeId: 'F31' },
            { FromNodeId: '13', ToNodeId: 'F26' },
            { FromNodeId: '14.1', ToNodeId: 'F19' },
            { FromNodeId: '14.2', ToNodeId: 'F20' },
            { FromNodeId: '15', ToNodeId: 'F21' },
            { FromNodeId: '16', ToNodeId: 'F19' },
            { FromNodeId: '17', ToNodeId: 'F8' },
            { FromNodeId: '18', ToNodeId: 'F26' },
            { FromNodeId: '20', ToNodeId: 'F31' },
            { FromNodeId: '21', ToNodeId: 'F33' },
            { FromNodeId: '22', ToNodeId: 'F36' },
            { FromNodeId: '23', ToNodeId: 'F39' },
            { FromNodeId: '24', ToNodeId: 'F38' },
            { FromNodeId: '25', ToNodeId: 'F41' },
            { FromNodeId: '26', ToNodeId: 'F42' },
            { FromNodeId: '27', ToNodeId: 'F47' },
            { FromNodeId: '27', ToNodeId: 'F42' },
            { FromNodeId: '28', ToNodeId: 'F47' },
            { FromNodeId: '28', ToNodeId: 'F28' },
            { FromNodeId: '29', ToNodeId: 'F9' },
            { FromNodeId: '10', ToNodeId: '11' },
            { FromNodeId: '18', ToNodeId: '19' }],
        TURN_RULES: [
            { from: '1.1', via: 'F4', to: '2', turn: 'Rẽ trái' },
            { from: '1.1', via: 'F4', to: 'F5', turn: 'Đi thẳng' },
            { from: '1.2', via: 'F7', to: 'F6', turn: 'Rẽ trái' },
            { from: '2', via: 'F4', to: 'F5', turn: 'Đi thẳng' },
            { from: '3', via: 'F6', to: 'F5', turn: 'Rẽ phải' },
            { from: '3', via: 'F6', to: 'F7', turn: 'Rẽ trái' },
            { from: '3', via: 'F8', to: '4', turn: 'Đi thẳng' },
            { from: '3', via: 'F8', to: '17', turn: 'Rẽ phải' },
            { from: '3', via: 'F8', to: 'F9', turn: 'Rẽ trái' },
            { from: '4', via: 'F8', to: '17', turn: 'Rẽ trái' },
            { from: '4', via: 'F8', to: 'F9', turn: 'Rẽ phải' },
            { from: '4', via: 'F8', to: '3', turn: 'Đi thẳng' },
            { from: '5', via: 'F10', to: 'F9', turn: 'Rẽ trái' },
            { from: '5', via: 'F10', to: 'F12', turn: 'Rẽ phải' },
            { from: '5', via: 'F10', to: 'F11', turn: 'Đi thẳng' },
            { from: '6', via: 'F11', to: '7', turn: 'Rẽ trái' },
            { from: '6', via: 'F11', to: 'F10', turn: 'Rẽ phải' },
            { from: '7', via: 'F11', to: 'F10', turn: 'Đi thẳng' },
            { from: '7', via: 'F11', to: '6', turn: 'Rẽ phải' },
            { from: '8.2', via: 'F12', to: 'F14', turn: 'Rẽ trái' },
            { from: '8.2', via: 'F12', to: 'F10', turn: 'Rẽ phải' },
            { from: '8.1', via: 'F13', to: '9', turn: 'Đi thẳng' },
            { from: '8.1', via: 'F13', to: 'F15', turn: 'Rẽ phải' },
            { from: '9', via: 'F13', to: '8.1', turn: 'Đi thẳng' },
            { from: '9', via: 'F13', to: 'F15', turn: 'Rẽ trái' },
            { from: '10', via: 'F14', to: 'F23', turn: 'Đi thẳng' },
            { from: '10', via: 'F14', to: 'F12', turn: 'Rẽ phải' },
            { from: '10', via: 'F14', to: 'F27', turn: 'Rẽ trái' },
            { from: '10', via: 'F15', to: 'F13', turn: 'Rẽ trái' },
            { from: '11', via: 'F27', to: '12.2', turn: 'Đi thẳng' },
            { from: '11', via: 'F27', to: 'F14', turn: 'Rẽ phải' },
            { from: '11', via: 'F27', to: 'F28', turn: 'Rẽ trái' },
            { from: '12.2', via: 'F27', to: 'F28', turn: 'Rẽ phải' },
            { from: '12.2', via: 'F27', to: 'F14', turn: 'Rẽ trái' },
            { from: '12.2', via: 'F27', to: '11', turn: 'Đi thẳng' },
            { from: '12.1', via: 'F26', to: '18', turn: 'Đi thẳng' },
            { from: '12.1', via: 'F26', to: '13', turn: 'Rẽ trái' },
            { from: '12.1', via: 'F26', to: 'F23', turn: 'Rẽ phải' },
            { from: '13', via: 'F31', to: 'F32', turn: 'Rẽ phải' },
            { from: '13', via: 'F31', to: 'F30', turn: 'Rẽ trái' },
            { from: '13', via: 'F26', to: '18', turn: 'Rẽ trái' },
            { from: '13', via: 'F26', to: '12.1', turn: 'Rẽ phải' },
            { from: '13', via: 'F26', to: 'F23', turn: 'Đi thẳng' },
            { from: '14.1', via: 'F19', to: '16', turn: 'Đi thẳng' },
            { from: '14.1', via: 'F19', to: 'F21', turn: 'Rẽ trái' },
            { from: '14.2', via: 'F20', to: 'F23', turn: 'Rẽ phải' },
            { from: '15', via: 'F21', to: 'F23', turn: 'Đi thẳng' },
            { from: '15', via: 'F21', to: 'F19', turn: 'Rẽ trái' },
            { from: '16', via: 'F19', to: '14.1', turn: 'Đi thẳng' },
            { from: '16', via: 'F19', to: 'F21', turn: 'Rẽ phải' },
            { from: '17', via: 'F8', to: '4', turn: 'Rẽ phải' },
            { from: '17', via: 'F8', to: '3', turn: 'Rẽ trái' },
            { from: '17', via: 'F8', to: 'F9', turn: 'Đi thẳng' },
            { from: '18', via: 'F26', to: '13', turn: 'Rẽ phải' },
            { from: '18', via: 'F26', to: '12.1', turn: 'Đi thẳng' },
            { from: '18', via: 'F26', to: 'F23', turn: 'Rẽ trái' },
            { from: '20', via: 'F31', to: 'F33', turn: 'Rẽ trái' },
            { from: '20', via: 'F31', to: '13', turn: 'Đi thẳng' },
            { from: '20', via: 'F31', to: 'F30', turn: 'Rẽ phải' },
            { from: '21', via: 'F33', to: 'F31', turn: 'Rẽ phải' },
            { from: '22', via: 'F36', to: 'F37', turn: 'Rẽ phải' },
            { from: '22', via: 'F36', to: 'F30', turn: 'Rẽ trái' },
            { from: '23', via: 'F39', to: 'F38', turn: 'Rẽ trái' },
            { from: '23', via: 'F39', to: 'F29', turn: 'Rẽ phải' },
            { from: '24', via: 'F38', to: 'F39', turn: 'Đi thẳng' },
            { from: '24', via: 'F38', to: 'F41', turn: 'Rẽ phải' },
            { from: '24', via: 'F38', to: 'F37', turn: 'Rẽ trái' },
            { from: '25', via: 'F41', to: 'F40', turn: 'Đi thẳng' },
            { from: '25', via: 'F41', to: 'F38', turn: 'Rẽ trái' },
            { from: '25', via: 'F41', to: 'F42', turn: 'Rẽ phải' },
            { from: '26', via: 'F42', to: '27', turn: 'Đi thẳng' },
            { from: '26', via: 'F42', to: 'F41', turn: 'Rẽ trái' },
            { from: '27', via: 'F47', to: '28', turn: 'Rẽ trái' },
            { from: '27', via: 'F42', to: '26', turn: 'Đi thẳng' },
            { from: '27', via: 'F42', to: 'F41', turn: 'Rẽ phải' },
            { from: '28', via: 'F47', to: '27', turn: 'Rẽ phải' },
            { from: '28', via: 'F28', to: 'F40', turn: 'Rẽ trái' },
            { from: '28', via: 'F28', to: 'F27', turn: 'Rẽ phải' },
            { from: '28', via: 'F28', to: 'F29', turn: 'Đi thẳng' },
            { from: '29', via: 'F9', to: 'F10', turn: 'Đi thẳng' },
            { from: '29', via: 'F9', to: 'F8', turn: 'Rẽ phải' },
            { from: 'F4', via: '1.1', to: '', turn: 'Đi thẳng' },
            { from: 'F7', via: '1.2', to: '', turn: 'Đi thẳng' },
            { from: 'F4', via: '2', to: '', turn: 'Đi thẳng' },
            { from: 'F6', via: '3', to: 'F8', turn: 'Đi thẳng' },
            { from: 'F8', via: '3', to: 'F6', turn: 'Đi thẳng' },
            { from: 'F8', via: '4', to: '', turn: 'Đi thẳng' },
            { from: 'F10', via: '5', to: '', turn: 'Đi thẳng' },
            { from: 'F11', via: '6', to: '', turn: 'Đi thẳng' },
            { from: 'F11', via: '7', to: '', turn: 'Đi thẳng' },
            { from: 'F12', via: '8.2', to: '', turn: 'Đi thẳng' },
            { from: 'F13', via: '8.1', to: '', turn: 'Đi thẳng' },
            { from: 'F13', via: '9', to: '', turn: 'Đi thẳng' },
            { from: 'F14', via: '10', to: 'F15', turn: 'Đi thẳng' },
            { from: 'F15', via: '10', to: 'F14', turn: 'Đi thẳng' },
            { from: 'F27', via: '11', to: '10', turn: 'Rẽ trái' },
            { from: 'F27', via: '12.2', to: '', turn: 'Đi thẳng' },
            { from: 'F26', via: '12.1', to: '', turn: 'Đi thẳng' },
            { from: 'F31', via: '13', to: 'F26', turn: 'Đi thẳng' },
            { from: 'F26', via: '13', to: 'F31', turn: 'Đi thẳng' },
            { from: 'F19', via: '14.1', to: '', turn: 'Đi thẳng' },
            { from: 'F20', via: '14.2', to: '', turn: 'Đi thẳng' },
            { from: 'F21', via: '15', to: '', turn: 'Đi thẳng' },
            { from: 'F19', via: '16', to: '', turn: 'Đi thẳng' },
            { from: 'F8', via: '17', to: '', turn: 'Đi thẳng' },
            { from: 'F26', via: '18', to: '', turn: 'Đi thẳng' },
            { from: 'F31', via: '20', to: '', turn: 'Đi thẳng' },
            { from: 'F33', via: '21', to: '', turn: 'Đi thẳng' },
            { from: 'F36', via: '22', to: '', turn: 'Đi thẳng' },
            { from: 'F39', via: '23', to: '', turn: 'Đi thẳng' },
            { from: 'F38', via: '24', to: '', turn: 'Đi thẳng' },
            { from: 'F41', via: '25', to: '', turn: 'Đi thẳng' },
            { from: 'F42', via: '26', to: '', turn: 'Đi thẳng' },
            { from: 'F47', via: '27', to: 'F42', turn: 'Đi thẳng' },
            { from: 'F42', via: '27', to: 'F47', turn: 'Đi thẳng' },
            { from: 'F47', via: '28', to: 'F28', turn: 'Đi thẳng' },
            { from: 'F28', via: '28', to: 'F47', turn: 'Đi thẳng' },
            { from: 'F9', via: '29', to: '', turn: 'Đi thẳng' },
            { from: '10', via: '11', to: '27', turn: 'Rẽ phải' },
            { from: '18', via: '19', to: '', turn: 'Đi thẳng' },
            { from: '11', via: '10', to: 'F15', turn: 'Rẽ phải' },
            { from: '11', via: '10', to: 'F14', turn: 'Rẽ trái' },
            { from: '19', via: '18', to: '', turn: 'Đi thẳng' },
            { from: 'F4', via: 'F5', to: 'F6', turn: 'Rẽ PhảI' },
            { from: 'F5', via: 'F6', to: 'F7', turn: 'Đi Thẳng' },
            { from: 'F5', via: 'F6', to: '3', turn: 'Rẽ Trái' },
            { from: 'F6', via: 'F7', to: '1.2', turn: 'Rẽ PhảI' },
            { from: 'F6', via: '3', to: 'F8', turn: 'Đi Thẳng' },
            { from: 'F8', via: 'F9', to: '29', turn: 'Rẽ Trái' },
            { from: 'F8', via: 'F9', to: 'F10', turn: 'Rẽ PhảI' },
            { from: 'F9', via: 'F10', to: '5', turn: 'Rẽ PhảI' },
            { from: 'F9', via: 'F10', to: 'F11', turn: 'Rẽ Trái' },
            { from: 'F9', via: 'F10', to: 'F12', turn: 'Đi Thẳng' },
            { from: 'F10', via: 'F11', to: '6', turn: 'Rẽ Trái' },
            { from: 'F10', via: 'F11', to: '7', turn: 'Đi Thẳng' },
            { from: 'F10', via: 'F9', to: 'F8', turn: 'Rẽ Trái' },
            { from: 'F10', via: 'F9', to: '29', turn: 'Đi Thẳng' },
            { from: 'F10', via: 'F12', to: '8.2', turn: 'Rẽ Trái' },
            { from: 'F10', via: 'F12', to: 'F14', turn: 'Đi Thẳng' },
            { from: 'F12', via: 'F14', to: '10', turn: 'Rẽ Trái' },
            { from: 'F12', via: 'F14', to: 'F23', turn: 'Rẽ PhảI' },
            { from: 'F12', via: 'F14', to: 'F27', turn: 'Đi Thẳng' },
            { from: 'F12', via: 'F10', to: '5', turn: 'Rẽ Trái' },
            { from: 'F12', via: 'F10', to: 'F11', turn: 'Rẽ PhảI' },
            { from: 'F12', via: 'F10', to: 'F9', turn: 'Đi Thẳng' },
            { from: 'F13', via: 'F15', to: '10', turn: 'Rẽ PhảI' },
            { from: 'F14', via: 'F27', to: '11', turn: 'Rẽ Trái' },
            { from: 'F14', via: 'F27', to: '12.2', turn: 'Rẽ PhảI' },
            { from: 'F14', via: 'F23', to: 'F20', turn: 'Rẽ PhảI' },
            { from: 'F14', via: 'F27', to: 'F28', turn: 'Đi Thẳng' },
            { from: 'F14', via: 'F12', to: '8.2', turn: 'Rẽ PhảI' },
            { from: 'F14', via: 'F12', to: 'F10', turn: 'Đi Thẳng' },
            { from: 'F14', via: 'F23', to: 'F21', turn: 'Đi Thẳng' },
            { from: 'F14', via: 'F23', to: 'F26', turn: 'Rẽ Trái' },
            { from: 'F14', via: '10', to: 'F15', turn: 'Đi Thẳng' },
            { from: 'F14', via: '10', to: '11', turn: 'Rẽ PhảI' },
            { from: 'F19', via: 'F21', to: '15', turn: 'Rẽ PhảI' },
            { from: 'F19', via: 'F21', to: 'F23', turn: 'Rẽ Trái' },
            { from: 'F20', via: 'F23', to: 'F26', turn: 'Đi Thẳng' },
            { from: 'F20', via: 'F23', to: 'F21', turn: 'Rẽ PhảI' },
            { from: 'F20', via: 'F23', to: 'F14', turn: 'Rẽ Trái' },
            { from: 'F21', via: 'F23', to: 'F14', turn: 'Đi Thẳng' },
            { from: 'F21', via: 'F23', to: 'F26', turn: 'Rẽ PhảI' },
            { from: 'F21', via: 'F23', to: 'F20', turn: 'Rẽ Trái' },
            { from: 'F27', via: 'F28', to: 'F40', turn: 'Đi Thẳng' },
            { from: 'F27', via: 'F28', to: 'F29', turn: 'Rẽ PhảI' },
            { from: 'F27', via: 'F28', to: '28', turn: 'Rẽ Trái' },
            { from: 'F28', via: 'F29', to: 'F30', turn: 'Đi Thẳng' },
            { from: 'F28', via: 'F29', to: 'F39', turn: 'Rẽ Trái' },
            { from: 'F28', via: 'F40', to: 'F41', turn: 'Đi Thẳng' },
            { from: 'F29', via: 'F30', to: 'F31', turn: 'Đi Thẳng' },
            { from: 'F29', via: 'F30', to: 'F36', turn: 'Rẽ Trái' },
            { from: 'F29', via: 'F39', to: 'F38', turn: 'Đi Thẳng' },
            { from: 'F29', via: 'F39', to: '23', turn: 'Rẽ Trái' },
            { from: 'F30', via: 'F31', to: 'F33', turn: 'Đi Thẳng' },
            { from: 'F30', via: 'F31', to: '20', turn: 'Rẽ Trái' },
            { from: 'F30', via: 'F31', to: '13', turn: 'Rẽ PhảI' },
            { from: 'F30', via: 'F36', to: 'F37', turn: 'Đi Thẳng' },
            { from: 'F30', via: 'F36', to: '22', turn: 'Rẽ PhảI' },
            { from: 'F36', via: 'F37', to: 'F38', turn: 'Rẽ Trái' },
            { from: 'F37', via: 'F38', to: '24', turn: 'Rẽ PhảI' },
            { from: 'F37', via: 'F38', to: 'F39', turn: 'Rẽ Trái' },
            { from: 'F37', via: 'F38', to: 'F41', turn: 'Đi Thẳng' },
            { from: 'F38', via: 'F39', to: 'F29', turn: 'Đi Thẳng' },
            { from: 'F38', via: 'F39', to: '23', turn: 'Rẽ PhảI' },
            { from: 'F38', via: 'F41', to: '25', turn: 'Rẽ PhảI' },
            { from: 'F38', via: 'F41', to: 'F42', turn: 'Đi Thẳng' },
            { from: 'F38', via: 'F41', to: 'F40', turn: 'Rẽ Trái' },
            { from: 'F40', via: 'F41', to: '25', turn: 'Đi Thẳng' },
            { from: 'F40', via: 'F41', to: 'F38', turn: 'Rẽ PhảI' },
            { from: 'F40', via: 'F41', to: 'F42', turn: 'Rẽ Trái' },
            { from: 'F41', via: 'F42', to: '26', turn: 'Rẽ PhảI' },
            { from: 'F41', via: 'F42', to: '27', turn: 'Rẽ Trái' },
            { from: 'F5', via: 'F4', to: '2', turn: 'Rẽ PhảI' },
            { from: 'F5', via: 'F4', to: '1.1', turn: 'Đi Thẳng' },
            { from: 'F6', via: 'F5', to: 'F4', turn: 'Rẽ PhảI' },
            { from: 'F7', via: 'F6', to: '3', turn: 'Rẽ PhảI' },
            { from: 'F7', via: 'F6', to: 'F5', turn: 'Đi Thẳng' },
            { from: 'F9', via: 'F8', to: '3', turn: 'Rẽ PhảI' },
            { from: 'F9', via: 'F8', to: '4', turn: 'Rẽ Trái' },
            { from: 'F9', via: 'F8', to: '17', turn: 'Đi Thẳng' },
            { from: 'F11', via: 'F10', to: 'F9', turn: 'Rẽ PhảI' },
            { from: 'F11', via: 'F10', to: '5', turn: 'Đi Thẳng' },
            { from: 'F11', via: 'F10', to: 'F12', turn: 'Rẽ Trái' },
            { from: 'F15', via: 'F13', to: '9', turn: 'Rẽ PhảI' },
            { from: 'F15', via: 'F13', to: '8.1', turn: 'Rẽ Trái' },
            { from: 'F27', via: 'F14', to: 'F12', turn: 'Đi Thẳng' },
            { from: 'F27', via: 'F14', to: '10', turn: 'Rẽ PhảI' },
            { from: 'F27', via: 'F14', to: 'F23', turn: 'Rẽ Trái' },
            { from: 'F23', via: 'F14', to: '10', turn: 'Đi Thẳng' },
            { from: 'F23', via: 'F14', to: 'F12', turn: 'Rẽ Trái' },
            { from: 'F23', via: 'F14', to: 'F27', turn: 'Rẽ PhảI' },
            { from: 'F21', via: 'F19', to: '14.1', turn: 'Rẽ PhảI' },
            { from: 'F21', via: 'F19', to: '16', turn: 'Rẽ Trái' },
            { from: 'F23', via: 'F20', to: '14.2', turn: 'Rẽ Trái' },
            { from: 'F23', via: 'F21', to: 'F19', turn: 'Rẽ PhảI' },
            { from: 'F23', via: 'F21', to: '15', turn: 'Đi Thẳng' },
            { from: 'F23', via: 'F26', to: '13', turn: 'Đi Thẳng' },
            { from: 'F23', via: 'F26', to: '18', turn: 'Rẽ PhảI' },
            { from: 'F23', via: 'F26', to: '12.1', turn: 'Rẽ Trái' },
            { from: 'F28', via: 'F27', to: 'F14', turn: 'Đi Thẳng' },
            { from: 'F28', via: 'F27', to: '11', turn: 'Rẽ PhảI' },
            { from: 'F28', via: 'F27', to: '12.2', turn: 'Rẽ Trái' },
            { from: 'F29', via: 'F28', to: '28', turn: 'Đi Thẳng' },
            { from: 'F29', via: 'F28', to: 'F40', turn: 'Rẽ PhảI' },
            { from: 'F29', via: 'F28', to: 'F27', turn: 'Rẽ Trái' },
            { from: 'F40', via: 'F28', to: 'F27', turn: 'Đi Thẳng' },
            { from: 'F40', via: 'F28', to: 'F29', turn: 'Rẽ Trái' },
            { from: 'F40', via: 'F28', to: '28', turn: 'Rẽ PhảI' },
            { from: 'F30', via: 'F29', to: 'F39', turn: 'Rẽ PhảI' },
            { from: 'F30', via: 'F29', to: 'F28', turn: 'Đi Thẳng' },
            { from: 'F39', via: 'F29', to: 'F28', turn: 'Rẽ PhảI' },
            { from: 'F39', via: 'F29', to: 'F30', turn: 'Rẽ Trái' },
            { from: 'F31', via: 'F30', to: 'F29', turn: 'Đi Thẳng' },
            { from: 'F31', via: 'F30', to: 'F36', turn: 'Rẽ PhảI' },
            { from: 'F36', via: 'F30', to: 'F29', turn: 'Rẽ PhảI' },
            { from: 'F36', via: 'F30', to: 'F31', turn: 'Rẽ Trái' },
            { from: 'F37', via: 'F36', to: 'F30', turn: 'Đi Thẳng' },
            { from: 'F37', via: 'F36', to: '22', turn: 'Rẽ Trái' },
            { from: 'F38', via: 'F37', to: 'F36', turn: 'Rẽ PhảI' },
            { from: 'F39', via: 'F38', to: '24', turn: 'Đi Thẳng' },
            { from: 'F39', via: 'F38', to: 'F37', turn: 'Rẽ PhảI' },
            { from: 'F39', via: 'F38', to: 'F41', turn: 'Rẽ Trái' },
            { from: 'F41', via: 'F38', to: '24', turn: 'Rẽ Trái' },
            { from: 'F41', via: 'F38', to: 'F37', turn: 'Đi Thẳng' },
            { from: 'F41', via: 'F38', to: 'F39', turn: 'Rẽ PhảI' },
            { from: 'F41', via: 'F40', to: 'F28', turn: 'Đi Thẳng' },
            { from: 'F42', via: 'F41', to: 'F38', turn: 'Đi Thẳng' },
            { from: 'F42', via: 'F41', to: 'F40', turn: 'Rẽ PhảI' },
            { from: 'F42', via: 'F41', to: '25', turn: 'Rẽ Trái' }]
    };

    try {
        const nodesObj = {};
        rawData.nodes.forEach(n => {
            const id = n.Id || n.id;
            nodesObj[id] = {
                x: n.X !== undefined ? n.X : n.x,
                y: n.Y !== undefined ? n.Y : n.y,
                name: n.Name || n.name,
                type: (n.Type || n.type || '').toLowerCase()
            };

        });

        const edgesArr = [];
        rawData.edges.forEach(e => {
            const u = e.FromNodeId || e.fromNodeId;
            const v = e.ToNodeId || e.toNodeId;
            const w = e.Weight || e.weight || 1;
            edgesArr.push([u, v, w]);
            edgesArr.push([v, u, w]); // Đường 2 chiều
        });

        // TRẢ VỀ CẢ RULES
        return {
            nodes: nodesObj,
            connections: edgesArr,
            rules: rawData.TURN_RULES
        };

    } catch (err) {
        console.error(err);
        return null;
    }

}
